name: flutter_colorpicker_example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker:
    path: ../

flutter:
  uses-material-design: true

environment:                                                            
  sdk: ">=2.12.0-29.10.beta <3.0.0"
