name: flutter_colorpicker
description: A HSV(HSB)/HSL color picker inspired by chrome devtools and a material color picker for your flutter app.
version: 0.4.0-nullsafety.0
homepage: https://github.com/mchome/flutter_colorpicker

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"
  flutter: ">=1.24.0-10.2.pre <2.0.0"
